services:
  angelos-app:
    container_name: angelos-app
    image: "ghcr.io/ls1intum/angelos-app:latest"
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./knowledge:/app/knowledge
    #    env_file:
    #      - development.env
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    environment:
      # Weaviate Database
      - WEAVIATE_URL
      - WEAVIATE_PORT
      - KNOWLEDGE_BASE_FOLDER
      - QA_FOLDER
      # Development config
      - TEST_MODE
      - DELETE_BEFORE_INIT
      # Ollama
      - USE_OLLAMA
      - API_KEY
      - URL
      - GPU_URL
      - GPU_USER
      - GPU_PASSWORD
      - GPU_MODEL
      - GPU_EMBED_MODEL
      - GPU_HOST
      # OpenAI
      - OPENAI_API_KEY
      - OPENAI_MODEL
      - OPENAI_EMBEDDING_MODEL
      # Azure OpenAI
      - USE_AZURE=true
      - AZURE_OPENAI_API_KEY
      - AZURE_OPENAI_DEPLOYMENT
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_VERSION
      # Cohere
      - COHERE_API_KEY
      - COHERE_API_KEY_MULTI
      - COHERE_API_KEY_EN
      - API_ENDPOINT_KEY
      - ANGELOS_APP_API_KEY
      - EXPECTED_PASSWORD
      - EXPECTED_USERNAME
    networks:
      - angelos-network

networks:
  angelos-network:
    name: angelos-network
    driver: bridge
    external: true
