services:
  angelos-app:
    container_name: angelos-app
    image: "ghcr.io/ls1intum/angelos-app:latest"
    ports:
      - "8000:8000"
    restart: unless-stopped
    #    env_file:
    #      - development.env
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    networks:
      - angelos-network

networks:
  angelos-network:
    driver: "bridge"
